### PR TITLE
Updated Dockerfile

### PR DESCRIPTION
**Pull request by 1992lipu**
Converted entrypoint to a shell executable format by adding "dos2unix"

### CODE REVIEW

**Comment by 1992lipu** [comment]
I was unable to build the docker image without it. Adding dos2unix solved the issue for me. Are you able to create the docker image without it?

**Comment by siggy** [comment]
@1992lipu Confirmed I can build the Docker image:
```bash
$ docker build -t buoyantio/linkerd-viz:latest .
...
Successfully built f51e1d864dcf
Successfully tagged buoyantio/linkerd-viz:latest
```

What error are you seeing during Docker build?

**Comment by 1992lipu** [comment]
I was getting

'exec user process caused "no such file or directory"'

**Comment by siggy** [comment]
@1992lipu Was that `exec user process` on `docker build` or `docker run`? Mind sharing the command and full transcript of the process? Also, can you share the output of `docker version`?

**Pull request closed without merging**
